### ISSUE TITLE
Nesting of the array is lost

### ISSUE THREAD

**Issue by badsysadm** [smee/binary#22]
Thanks for the great library.
It seems I found a bug.

I'm creating a codec with a (repeated) function that has another codec nested within it. This nested codec uses the (header) function. 
And when trying to decode a message, the nesting of the array is lost.

Also, if I simply call a nested repeated without a header, I end up in an infinite loop on decoding.

Version "0.5.5"
Code to reproduce the problem:

```clojure
(def xxx
  (compile-codec (header :uint-le
                   (fn [_] (repeated :uint-le))
                   (fn [_] 5))))

(def yyy
  (compile-codec (header :uint-le
                   (fn [_] (repeated xxx))
                   (fn [_] 4))))

(comment "Infinite loop"
  (def xxx
    (compile-codec (repeated :uint-le)))
  (def yyy
    (compile-codec (repeated xxx)))
)

(let [buf (ByteArrayOutputStream.)]
  (.reset buf)
  (encode yyy buf [[7 8 9] [1 2 3]])
  (vec (.toByteArray buf)) ; [4 0 0 0 5 0 0 0 7 0 0 0 8 0 0 0 9 0 0 0 5 0 0 0 1 0 0 0 2 0 0 0 3 0 0 0]
  (decode yyy (ByteArrayInputStream. (.toByteArray buf))))
```
```
>>> [[7 8 9 5 1 2 3]]
```

**Comment by smee** [comment]
This isn't a bug:  `prefix` is a codec for more complex cases, where the prefix has more structure than a simple number. You are expected to use the information of the header to construct the respective `body` codec.

In your example you discard the header and use  `repeated` without any length restrictions, so the first use of `repeated` exhausted all values (reads until EOF).
So, either use the value of the header to read the correct number of values or use the simpler codec ` (repeated :uint-le :prefix :uint-le)`.
